# Generated by Django 5.1.4 on 2025-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='message',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
