# Generated by Django 5.1.4 on 2025-01-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymenthistory_trans_id_alter_paymenthistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='date_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
