# Generated by Django 5.1.4 on 2025-01-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymenthistory_date_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-date_on']},
        ),
    ]
