# Generated by Django 5.1.4 on 2025-01-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_wallet_invoice_user_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
