# Generated by Django 5.1.4 on 2025-01-05 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoy_name', models.CharField(max_length=100, unique=True)),
                ('created_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_banner', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('event_key', models.CharField(max_length=100)),
                ('held_on', models.DateField(auto_now_add=True)),
                ('upload_limit', models.IntegerField(default=0)),
                ('selfie_limit', models.IntegerField(default=0)),
                ('ai_matches', models.IntegerField(default=0)),
                ('ai_matches_limit', models.IntegerField(default=0)),
                ('photo_selection_limit', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('valid_date', models.IntegerField(default=30, help_text='In Days')),
                ('event_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.event_categories')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.pricingfeatures')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='event_uploads/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.events')),
            ],
        ),
    ]
