# Generated by Django 5.1.4 on 2025-01-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_events_valid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_categories',
            name='default_credits',
            field=models.IntegerField(blank=True, default=150, null=True),
        ),
    ]
