# Generated by Django 5.1.4 on 2025-01-05 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100, unique=True)),
                ('pricing', models.FloatField(default=0.0)),
                ('website_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='pricingFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('upload_limit', models.IntegerField(default=0)),
                ('selfie_limit', models.IntegerField(default=0)),
                ('ai_matches', models.IntegerField(default=0)),
                ('photo_selection', models.BooleanField(default=False)),
                ('photo_selection_limit', models.IntegerField(default=0)),
                ('analytics_report', models.BooleanField(default=False)),
                ('support', models.CharField(choices=[('chat', 'Chat Support'), ('call', 'Call Support'), ('remote', 'Call + Anydesk')], max_length=100)),
                ('e_album', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='app.pricingplans')),
            ],
        ),
    ]
