# Generated by Django 5.1.4 on 2024-12-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingfeatures',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
