# Generated by Django 5.1.4 on 2025-01-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingfeatures',
            name='valid_date',
            field=models.IntegerField(default=30, help_text='In Days'),
        ),
    ]
