# Generated by Django 5.1.4 on 2025-01-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pricingfeatures_valid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplans',
            name='is_premium',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
