# Generated by Django 5.1.4 on 2025-01-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pricingplans_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplans',
            name='descriptino',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingplans',
            name='yearly_princing',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
