# Generated by Django 5.1.4 on 2025-01-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pricingplans_descriptino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplans',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlanFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('feature_name', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app.pricingplans')),
            ],
        ),
    ]
