# Generated by Django 5.1.4 on 2025-01-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pricingplans_is_premium_planfeatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplans',
            name='pricing',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pricingplans',
            name='yearly_princing',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
