# Generated by Django 5.1.4 on 2025-01-05 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verifyed', models.BooleanField(default=False)),
                ('email_token', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.FloatField(default=0.0)),
                ('refferel_points', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.pricingplans')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refferel_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reffered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refferels', to=settings.AUTH_USER_MODEL)),
                ('reffered_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reffere_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refferel_tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('refferel_points', models.IntegerField(default=10)),
                ('assinged_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrel_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
