# Generated by Django 5.1.4 on 2025-01-09 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_balance'),
        ('app', '0006_alter_pricingplans_pricing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.pricingplans'),
        ),
        migrations.AlterField(
            model_name='refferel_data',
            name='reffered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reffered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refferel_data',
            name='reffered_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reffered_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
