# Generated by Django 5.1.4 on 2025-01-09 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_plan_alter_refferel_data_reffered_by_and_more'),
        ('app', '0006_alter_pricingplans_pricing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.pricingplans'),
        ),
    ]
