# Generated by Django 5.1.4 on 2025-01-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='refferel_tokens',
            name='refferel_points',
            field=models.IntegerField(default=150),
        ),
    ]
